[toolchain]
channel = "stable"

[target.x86_64-pc-windows-msvc]
channel = "nightly"

[target.x86_64-pc-windows-gnu]
channel = "nightly"

# 32ビット Windows (optional)
[target.i686-pc-windows-msvc]
channel = "nightly"

[target.i686-pc-windows-gnu]
channel = "nightly"
