name: Cargo Build & Test

on:
  push:
  pull_request:

jobs:
  build_and_test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
          - windows
    steps:
      - uses: actions/checkout@v5
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack
      - name: Set up nightly toolchain (Windows)
        if: matrix.os == 'windows'
        run: rustup update nightly && rustup default nightly
      - name: Build project
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Check CLI tool
        run: |
          cargo install --path . 
          gpscan . 2> error.log 1> output.gpscan
      - uses: actions/upload-artifact@v5
        with:
          name: scan-results-${{ matrix.os }}
          path: |
            output.gpscan
            error.log
